# Build settings
markdown: redcarpet
highlighter: pygments

# Site settings
title: "Read this."
description: > # this means to ignore newlines until "email:"
   Awesome blog, hopefully

email: baruch@tabanpour.info
#blog logo
logo: "/assets/images/avatar.jpg"
# blog cover
cover: "/assets/images/bg.jpg"

name: 'Baruch'
author: 'Baruch'
author_image: "/assets/images/avatar.jpg"

paginate:	5

url: "http://blog.tabanpour.info" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/btabanpour
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: //www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/btaba
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
