# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

sass:
  style: compact # possible values: nested expanded compact compressed

# Site settings
title: "words and other content"
description: > # this means to ignore newlines until "email:"
  by baruch

email: baruch@tabanpour.info
#blog logo
logo: "/assets/images/avatar.jpg"
# blog cover
cover: "/assets/images/coz-castel-matin.jpg"

name: 'Baruch Tabanpour'
author: 'Baruch Tabanpour'
author_image: "/assets/images/avatar.jpg"

url: "http://blog.tabanpour.info" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:

  # - icon: soundcloud
  #   url: https://soundcloud.com/user-182551466

  - icon:	twitter
    url:	https://twitter.com/btabanpour
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  # - icon:  instagram
  #   url: https://instagram.com/bartabelix/
  #   desc: Connect with me on instagram
  #   share_url:
  #   share_title:
  #   share_link:

  - icon:	github
    url:	https://github.com/btaba
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

  - icon: foursquare
    url: https://foursquare.com/user/194675285
